apiVersion: apps/v1
kind: Deployment
metadata:
	name: portfolio-backend
spec:
	replicas: 1
	selector:
		matchLabels:
			app: portfolio-backend
	template:
		metadata:
			labels:
				app: portfolio-backend
		spec:
			containers:
				- name: backend
					image: portfolio-backend:latest
					imagePullPolicy: IfNotPresent
					env:
						- name: AUTO_CREATE_DB
						  value: "true"
						- name: DATABASE_URL
						  value: postgresql://postgres:postgres@postgres:5432/app
					envFrom:
						- secretRef:
							name: portfolio-backend-secret
						- secretRef:
							name: portfolio-openai
					ports:
						- containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
	name: portfolio-backend
spec:
	type: ClusterIP
	selector:
		app: portfolio-backend
	ports:
		- port: 80
		  targetPort: 5000

