apiVersion: v1
kind: Secret
metadata:
	name: portfolio-backend-secret
type: Opaque
stringData:
	SECRET_KEY: change-this-in-prod
	JWT_SECRET_KEY: change-jwt-secret
	OAUTH_REDIRECT_URI: http://portfolio.local/oauth/callback
	GITHUB_CLIENT_ID: ""
	GITHUB_CLIENT_SECRET: ""
	GITLAB_CLIENT_ID: ""
	GITLAB_CLIENT_SECRET: ""

