"""init schema

Revision ID: 976ddde32720
Revises: 
Create Date: 2025-08-19 22:05:40.400071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976ddde32720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_path', sa.String(length=512), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kanban_column_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_kanban_column_id'), ['kanban_column_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_kanban_column_id', 'kanban_columns', ['kanban_column_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_kanban_column_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_kanban_column_id'))
        batch_op.drop_column('kanban_column_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('roadmap_path')

    # ### end Alembic commands ###
