name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        working-directory: project-portfolio/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke test
        working-directory: project-portfolio/backend
        env:
          AUTO_CREATE_DB: 'true'
          DATABASE_URL: 'sqlite:///app.db'
          PYTHONPATH: ${{ github.workspace }}/project-portfolio/backend
        run: |
          python - <<'PY'
          import os
          os.environ.setdefault('AUTO_CREATE_DB','true')
          os.environ.setdefault('DATABASE_URL','sqlite:///app.db')
          from app import create_app
          app = create_app()
          print('Backend app created OK')
          PY
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: project-portfolio/frontend/package-lock.json
      - name: Install and build
        working-directory: project-portfolio/frontend
        run: |
          npm ci
          npm run build
